### PR TITLE
Prevent false negatives in master CI

### PR DESCRIPTION
**Pull request by MattiSG**
* Technical improvement.
* Impacted areas: CI & deployment
* Details:
  - The current instruction set used to try to deploy to Pypi on each merge to `master`; however, no Pypi user was set up. This changeset stops trying to deploy altogether.
  - Improve repository readability by moving CI scripts to a specific directory.

- - - -

These changes:

- Change non-functional parts of this repository (for instance editing the README)

### CODE REVIEW

**Comment by Br3nda** [comment]
Should we wait for circleci?

**Comment by MattiSG** [comment]
No, that has to do with the way the new CircleCI version apparently now scopes build reports. I will change the required status report to the proper scope :)

**Comment by MattiSG** [comment]
Done! Only missing a review now 🙂

**Comment by MattiSG** [comment]
Using admin privileges to merge without review as this has no functional impact and the effectiveness of the change can be checked on CircleCI.

**Pull request merged**
